/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelRitmoRouteImport } from './routes/panel.ritmo'
import { Route as PanelPosicionesRouteImport } from './routes/panel.posiciones'
import { Route as PanelPilotosRouteImport } from './routes/panel.pilotos'
import { Route as PanelNeumaticosRouteImport } from './routes/panel.neumaticos'
import { Route as PanelMapaRouteImport } from './routes/panel.mapa'
import { Route as PanelEquiposRouteImport } from './routes/panel.equipos'
import { Route as PanelClasificacionRouteImport } from './routes/panel.clasificacion'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRitmoRoute = PanelRitmoRouteImport.update({
  id: '/ritmo',
  path: '/ritmo',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPosicionesRoute = PanelPosicionesRouteImport.update({
  id: '/posiciones',
  path: '/posiciones',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPilotosRoute = PanelPilotosRouteImport.update({
  id: '/pilotos',
  path: '/pilotos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelNeumaticosRoute = PanelNeumaticosRouteImport.update({
  id: '/neumaticos',
  path: '/neumaticos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMapaRoute = PanelMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEquiposRoute = PanelEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelClasificacionRoute = PanelClasificacionRouteImport.update({
  id: '/clasificacion',
  path: '/clasificacion',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/clasificacion': typeof PanelClasificacionRoute
  '/panel/equipos': typeof PanelEquiposRoute
  '/panel/mapa': typeof PanelMapaRoute
  '/panel/neumaticos': typeof PanelNeumaticosRoute
  '/panel/pilotos': typeof PanelPilotosRoute
  '/panel/posiciones': typeof PanelPosicionesRoute
  '/panel/ritmo': typeof PanelRitmoRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel/clasificacion': typeof PanelClasificacionRoute
  '/panel/equipos': typeof PanelEquiposRoute
  '/panel/mapa': typeof PanelMapaRoute
  '/panel/neumaticos': typeof PanelNeumaticosRoute
  '/panel/pilotos': typeof PanelPilotosRoute
  '/panel/posiciones': typeof PanelPosicionesRoute
  '/panel/ritmo': typeof PanelRitmoRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/clasificacion': typeof PanelClasificacionRoute
  '/panel/equipos': typeof PanelEquiposRoute
  '/panel/mapa': typeof PanelMapaRoute
  '/panel/neumaticos': typeof PanelNeumaticosRoute
  '/panel/pilotos': typeof PanelPilotosRoute
  '/panel/posiciones': typeof PanelPosicionesRoute
  '/panel/ritmo': typeof PanelRitmoRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/panel/clasificacion'
    | '/panel/equipos'
    | '/panel/mapa'
    | '/panel/neumaticos'
    | '/panel/pilotos'
    | '/panel/posiciones'
    | '/panel/ritmo'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel/clasificacion'
    | '/panel/equipos'
    | '/panel/mapa'
    | '/panel/neumaticos'
    | '/panel/pilotos'
    | '/panel/posiciones'
    | '/panel/ritmo'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/panel/clasificacion'
    | '/panel/equipos'
    | '/panel/mapa'
    | '/panel/neumaticos'
    | '/panel/pilotos'
    | '/panel/posiciones'
    | '/panel/ritmo'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/ritmo': {
      id: '/panel/ritmo'
      path: '/ritmo'
      fullPath: '/panel/ritmo'
      preLoaderRoute: typeof PanelRitmoRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/posiciones': {
      id: '/panel/posiciones'
      path: '/posiciones'
      fullPath: '/panel/posiciones'
      preLoaderRoute: typeof PanelPosicionesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/pilotos': {
      id: '/panel/pilotos'
      path: '/pilotos'
      fullPath: '/panel/pilotos'
      preLoaderRoute: typeof PanelPilotosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/neumaticos': {
      id: '/panel/neumaticos'
      path: '/neumaticos'
      fullPath: '/panel/neumaticos'
      preLoaderRoute: typeof PanelNeumaticosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/mapa': {
      id: '/panel/mapa'
      path: '/mapa'
      fullPath: '/panel/mapa'
      preLoaderRoute: typeof PanelMapaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/equipos': {
      id: '/panel/equipos'
      path: '/equipos'
      fullPath: '/panel/equipos'
      preLoaderRoute: typeof PanelEquiposRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/clasificacion': {
      id: '/panel/clasificacion'
      path: '/clasificacion'
      fullPath: '/panel/clasificacion'
      preLoaderRoute: typeof PanelClasificacionRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelClasificacionRoute: typeof PanelClasificacionRoute
  PanelEquiposRoute: typeof PanelEquiposRoute
  PanelMapaRoute: typeof PanelMapaRoute
  PanelNeumaticosRoute: typeof PanelNeumaticosRoute
  PanelPilotosRoute: typeof PanelPilotosRoute
  PanelPosicionesRoute: typeof PanelPosicionesRoute
  PanelRitmoRoute: typeof PanelRitmoRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelClasificacionRoute: PanelClasificacionRoute,
  PanelEquiposRoute: PanelEquiposRoute,
  PanelMapaRoute: PanelMapaRoute,
  PanelNeumaticosRoute: PanelNeumaticosRoute,
  PanelPilotosRoute: PanelPilotosRoute,
  PanelPosicionesRoute: PanelPosicionesRoute,
  PanelRitmoRoute: PanelRitmoRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
